# Generated by Django 3.0.2 on 2020-03-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=50)),
                ('price_range', models.CharField(max_length=4)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Address')),
            ],
            options={
                'unique_together': {('restaurant_name', 'address_id')},
            },
        ),
        migrations.CreateModel(
            name='BestSellingItem',
            fields=[
                ('best_selling_item_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurants.Restaurant')),
                ('item_name', models.CharField(max_length=50)),
                ('item_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('coordinates_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurants.Restaurant')),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=16)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='RatingStats',
            fields=[
                ('rating_stats_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurants.Restaurant')),
                ('aggregate_rating', models.FloatField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('recommended', models.BooleanField(default=False)),
            ],
        ),
    ]
