# Generated by Django 3.0.2 on 2020-03-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200330_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(max_length=10),
        ),
    ]
