# Generated by Django 3.0.2 on 2020-04-01 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0003_auto_20200330_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerAccount',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MatchManagerToRestaurant',
            fields=[
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurants.Restaurant')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_management.ManagerAccount')),
            ],
        ),
    ]
