# Generated by Django 3.0.2 on 2020-03-28 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellingItem',
            fields=[
                ('item_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nationality', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentType',
            fields=[
                ('establishment_type_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('atmosphere', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('food_category_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('disclaimer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RatingStats',
            fields=[
                ('rating_stats_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('num_of_reviews', models.IntegerField(default=0)),
                ('recommended', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=20)),
                ('price_range', models.CharField(max_length=4)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Address')),
                ('best_selling_item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.BestSellingItem')),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.Cuisine')),
                ('establishment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.EstablishmentType')),
                ('food_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.FoodCategory')),
                ('rating_stats_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.RatingStats')),
            ],
            options={
                'unique_together': {('restaurant_name', 'address_id')},
            },
        ),
        migrations.AddField(
            model_name='establishmenttype',
            name='food_category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.FoodCategory'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='food_category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.FoodCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='establishmenttype',
            unique_together={('food_category_name', 'atmosphere')},
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=10)),
                ('expiry_date', models.DateTimeField()),
                ('details', models.CharField(max_length=200)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
            options={
                'unique_together': {('discount_code', 'restaurant_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cuisine',
            unique_together={('food_category_name', 'nationality')},
        ),
    ]
