# Generated by Django 3.0.2 on 2020-03-27 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellerItem',
            fields=[
                ('item_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('food_category_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('disclaimer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationBenchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('num_of_reviews', models.IntegerField()),
                ('recommended', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atmosphere', models.CharField(max_length=20)),
                ('food_category_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurants.FoodCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=20)),
                ('food_category_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurants.FoodCategory')),
            ],
        ),
    ]
