# Generated by Django 3.0.2 on 2020-03-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestDB',
            fields=[
                ('test', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=3)),
            ],
        ),
    ]
