# Generated by Django 3.0.2 on 2020-03-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20200330_0419'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcode',
            unique_together=set(),
        ),
    ]
